# Generated by Django 3.0 on 2021-01-05 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shadowapi', '0002_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='shadowapi.Register'),
            preserve_default=False,
        ),
    ]
